version: '3'

services:
  consul-server-1: &consul-server
    image: consul:latest
    networks:
      - substrate-ops
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-3:
    <<: *consul-server

  consul-server-4:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  monitor:
    image: darwinianetwork/monitor:0.1
    environment:
      NETWORK_NODE: 'darwinia'
      CONSUL_ADDRESS: http://consul-server-bootstrap:8500
      CONSUL_DC: 'dc1'
      DING_TALK_TOKEN: ''
    networks:
      - substrate-ops
    ports:
      - "24855:24855"
    command: ["./monitor"]

networks:
  substrate-ops:
    external: true