version: '3'

services:
  ops:
    build: .
    image: darwinianetwork/ops
    environment:
      CLIENT_NODE_PORT: 20222
    volumes:
      - ./config/config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: "python client.py start"
    networks:
      - substrate-ops


networks:
  substrate-ops:
    external: true